name: push feat to dev

permissions:
  contents: write

on:
  pull_request:
    branches: [ feat ]
    types: [ closed ]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # feat 변경사항 dev로 이동
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: |
          git checkout dev
          
          git merge feat
          
          # 실제 push 작업 수행
          git push origin dev
