name: push feat to dev

on:
  pull_request:
    branches: [ feat ]
    types: [ closed ]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # feat 변경사항 dev로 이동
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: push feat to dev
        env:
          TOKEN: x-access-token:${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: SWYP-Woory/woory-backend
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          
          # remote url 변경
          git config remote.origin.url "https://$TOKEN@github.com/$REPOSITORY.git"
          
          # 실제 push 작업 수행
          git push origin feat:dev